#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/myapp/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/myapp/manage.py makemigrations'"
python "$OPENSHIFT_REPO_DIR"manage.py makemigrations --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/myapp/manage.py migrate'"
python "$OPENSHIFT_REPO_DIR"manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/myapp/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"manage.py collectstatic --noinput
