#!/bin/bash
#this one is the deploy hook .openshift/action_hooks/deploy

source python2.7/bin/activate
source $OPENSHIFT_HOMEDIR/python/virtenv/venv/bin/activate

cd $OPENSHIFT_REPO_DIR
echo "Executing 'python manage.py migrate'"
python2.7 manage.py migrate
echo "Executing 'python manage.py collectstatic --noinput'"
python2.7 manage.py collectstatic --noinput

########################### end of file
